name: main

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Binary
      run: make build
    
    - name: Run Tests
      run: make test
    
    - name: Login to Docker Hub
      if: github.ref_type == 'tag'
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Image
      if: github.ref_type == 'tag'
      run: |
        docker build . -t weaveworks/weave-iac-validator:${{ github.ref_name }}
        docker push weaveworks/weave-iac-validator:${{ github.ref_name }}
        docker build . -t weaveworks/weave-iac-validator:${{ github.ref_name }}-azure
        docker push weaveworks/weave-iac-validator:${{ github.ref_name }}-azure