name: release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Build Binary
      run: make build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Image
      run: |
        docker build . -t weaveworks/weave-policy-validator:${{ github.ref_name }}
        docker push weaveworks/weave-policy-validator:${{ github.ref_name }}

    - name: Build and Push Azure Image
      working-directory: ./azure
      run: |
        docker build . -t weaveworks/weave-policy-validator:${{ github.ref_name }}-azure
        docker push weaveworks/weave-policy-validator:${{ github.ref_name }}-azure
